### ISSUE TITLE
マルチモジュール

### ISSUE THREAD

**Issue by mag0716** [mag0716/Android#64]
## 概要

マルチモジュールのプロジェクト構成を検証する。

マルチモジュールにする理由は

* ビルド時間を減らす
* 構成自体で設計の制約を持たせることでどこに実装するのかを制限し、初期開発者以外の改修、機能追加時の設計の破綻をなくしたい
* Android への依存(特に Context) を減らしてテストを容易にしたい(Robolectric との戦いを減らしたい)

ただし、いろいろなレベルのエンジニア、流動的なチームを想定し、あまり複雑にせず学習コストも限りなく少なくする必要がある
また、Instant Apps, Dynamic Module は現時点では考えないが、最終的には考慮する必要がある

## 検証内容

- [x] 参考文献
- [x] なぜ導入したいのかをまとめる
- [x] マルチモジュールのアプリを作成
    * API を使う
    * 一覧と詳細画面を表示する
    * 画面表示時にデータを取得する
- [x] ブラッシュアップ
    - [x] どういう単位でモジュール化するべきか？(#66)
    - [x] (未対応) app のアーキテクチャはどうしよう？
        * アーキテクチャはアプリの規模、性質、チームのレベルに依存するので固定しない
    - [x] 可能であれば、app モジュール以外はライブラリに依存させたくない
        * Rx 系もできれば
    - [x] 可能であれば、View 以外は Android に依存させないようにしたい(#79)
        - [x] api
        - [x] datasource
        - [x] usecase
    - [x] Proguard (#80)
    - [x] 複数 flavor を定義 (#81)
    - [x] ロギング(#69)
        * Timber に依存させると、Android に依存することになる？(#75)
            * 5.0.0-SNAPSHOT で MPP をサポートしたので解決！！
    - [x] Instants App(mag0716/Google_IO_2018_CatchUp#64)
         * Android App Bundle でだいぶ楽になった。Dynamic Module とほぼ同じ
    - [x] Dynamic Module
        * レイヤー単位でモジュール化した場合、複数のモジュールを一気に取得することは可能なの？
        -> 可能(https://github.com/mag0716/Google_IO_2018_CatchUp/pull/63)

### 要検証

- [x] テスト(#87)
    * 一度に複数モジュールのテストを実施する方法
- [x] Dynamic Feature Module 
    * 組み込み形式で使っても beta 登録が必要？
- [x] DI 周り
    * Module をそれぞれのモジュールに持たせる方法でよいか
    * https://medium.com/androiddevelopers/dependency-injection-in-a-multi-module-project-1a09511c14b7

### 悩み中

* resources モジュールはいる？
    * ビルドは早くなるかもしれないが、検索がしづらくなりそうなので一旦対応しない
* ui モジュールは別に作るべき？
    * モジュールが増えすぎるので作らない
* 永続化領域の本体はどこで実装する？
    * Android に依存するモジュールを増やしたくないので、app にしたい
* Navigation Graph はどこで持つ？
    * https://blog.usejournal.com/multi-module-navigation-with-the-android-architecture-component-82ed028fa1d9
    * https://medium.com/google-developer-experts/using-navigation-architecture-component-in-a-large-banking-app-ac84936a42c2

## 関連

- [x] api vs implementation
    * https://medium.com/mindorks/implementation-vs-api-in-gradle-3-0-494c817a6fa
- [x] API 実行時に coroutines を利用する
    * https://github.com/JakeWharton/retrofit2-kotlin-coroutines-adapter
    * https://qiita.com/hossynohito/items/27e10df1b331e077161a

**Comment by mag0716** [comment]
## coroutines

* https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-coroutine-scope/index.html

**Comment by mag0716** [comment]
## feature 間の遷移(依存)をどうするか？

https://proandroiddev.com/dynamic-feature-module-with-dependency-less-navigation-koin-774694f41f63

**Comment by mag0716** [comment]
usecase：「何かのインプットやアクションを受け取ったら、何かしらの処理をして、アウトプットや通知をする」

**Comment by mag0716** [comment]
apk なら Dynamic Feature Module を beta 申請なしで利用できるが、
`./gradlew assemble` で生成した apk には Dynamic Feature Module は含まれないので、bundletool を経由する必要がある。

**Comment by mag0716** [comment]
残件：README 更新
